---
kind: pipeline
name: checkers
steps:
  - name: compatibility
    image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
    environment:
      APP_NAME: ldap_write_support
      CORE_BRANCH: stable26
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
type: docker
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: integration-master
steps:
  - name: integration
    image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
    environment:
      APP_NAME: ldap_write_support
      CORE_BRANCH: stable26
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - php occ config:system:set redis host --value=cache
      - php occ config:system:set redis port --value=6379 --type=integer
      - php occ config:system:set redis timeout --value=0 --type=integer
      - php occ config:system:set --type string --value "\\OC\\Memcache\\Redis" memcache.local
      - php occ config:system:set --type string --value "\\OC\\Memcache\\Redis" memcache.distributed
      - php occ app:enable user_ldap
      - php occ app:enable $APP_NAME
      - cd apps/$APP_NAME
      - cd tests/integration
      - ./run.sh

services:
  - name: cache
    image: ghcr.io/nextcloud/continuous-integration-redis:latest
  - name: openldap
    image: ghcr.io/nextcloud/continuous-integration-openldap:openldap-7
    environment:
      SLAPD_DOMAIN: nextcloud.ci
      SLAPD_ORGANIZATION: Nextcloud
      SLAPD_PASSWORD: admin
      SLAPD_ADDITIONAL_MODULES: memberof

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
type: docker

---
kind: pipeline
name: integration-master-nocache
steps:
  - name: integration
    image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
    environment:
      APP_NAME: ldap_write_support
      CORE_BRANCH: stable26
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - php occ app:enable user_ldap
      - php occ app:enable $APP_NAME
      - cd apps/$APP_NAME
      - cd tests/integration
      - ./run.sh

services:
  - name: openldap
    image: ghcr.io/nextcloud/continuous-integration-openldap:openldap-7
    environment:
      SLAPD_DOMAIN: nextcloud.ci
      SLAPD_ORGANIZATION: Nextcloud
      SLAPD_PASSWORD: admin
      SLAPD_ADDITIONAL_MODULES: memberof

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
type: docker
---
kind: signature
hmac: 3972c46c835f38d2514fb4ce5f5cf830035235af883197fc5c190996829ae0d1

...
